### ISSUE TITLE
Bug: Auto-filled answer and marked complete (How?, Why?)

### ISSUE THREAD

**Issue by Lewiscowles1986** [christianp/30secondchallenge#2]
Was just restarting my dailies and while I was on x8 it suddenly autofilled and marked incorrect (v.annoying)

![screenshot capture - 2018-03-25 - 15-39-04](https://user-images.githubusercontent.com/2605791/37876342-da29e5a0-3042-11e8-9ea8-631e4dfc82f4.png)

**Comment by christianp** [comment]
That's when the timer runs out. You can remove the time limit by dragging the slider all the way to the right.
